[library]
[library.cshoremodel]
language = "fortran"
library = "bmi_cshore_module"
header = ""
entry_point = "bmi_cshore_type"

[build]
undef_macros = []
define_macros = []
libraries = []
library_dirs = []
include_dirs = []
extra_compile_args = []
max_instances = 1

[package]
name = "pymt_cshore"
requirements = [""]

[info]
github_username = "pymt-lab"
package_author = "csdms"
package_author_email = "csdms@colorado.edu"
package_license = "MIT"
summary = "PyMT plugin for heat model"

[ci]
python_version = ["3.9"]
os = ["linux"]
